const data = [
  {
    id: 1,
    first_name: "Marie",
    last_name: "Antoinette",
    email: "antoinette@gmail.com",
    gender: "Female",
    ip_address: "26.16.10.231",
    address: "Tai Po",
    photo: "https://robohash.org/voluptasipsaharum.bmp?size=50x50&set=set1",
    company: "Knowledge",
    department: "Services",
    Salary: "20000",
    about: "React",
  },
  {
    id: 2,
    first_name: "Anthony",
    last_name: "Bourdain",
    email: "tonybourdain@gmail.com",
    gender: "Male",
    ip_address: "179.76.60.195",
    address: "Rancaranji",
    photo: "https://robohash.org/utquasicorrupti.bmp?size=50x50&set=set1",
    company: "Knowledge",
    department: "Sales",
    Salary: "20000",
    about: "React",
  },
  {
    id: 3,
    first_name: "Claire",
    last_name: "Devenport",
    email: "ddev@gmail.com",
    gender: "Female",
    ip_address: "54.99.71.1",
    address: "Calilegua",
    photo: "https://robohash.org/dolorumsedqui.png?size=50x50&set=set1",
    company: "Knowledge",
    department: "Services",
    Salary: "20000",
    about: "Node.js",
  },
  {
    id: 4,
    first_name: "Don",
    last_name: "Draper",
    email: "dondraper@gmail.com",
    gender: "Male",
    ip_address: "105.254.37.138",
    address: "Cincinnati",
    photo: "https://robohash.org/facereeteligendi.jpg?size=50x50&set=set1",
    company: "Knowledge",
    department: "Services",
    Salary: "20000",
    about: "SQL",
  },
  {
    id: 5,
    first_name: "Roger",
    last_name: "Sterling",
    email: "rsterling@gmail.com",
    gender: "Male",
    ip_address: "97.158.192.125",
    address: "Jacaltenango",
    photo: "https://robohash.org/velitistecum.bmp?size=50x50&set=set1",
    company: "Knowledge",
    department: "Human Resources",
    Salary: "20000",
    about: "Groovy",
  },
  {
    id: 6,
    first_name: "Peggi",
    last_name: "Olson",
    email: "polson@gmail.com",
    gender: "Female",
    ip_address: "183.226.233.100",
    address: "Kopong",
    photo: "https://robohash.org/omnissequinemo.bmp?size=50x50&set=set1",
    company: "Knowledge",
    department: "Human Resources",
    Salary: "20000",
    about: "Next.js",
  },
  {
    id: 7,
    first_name: "Colette",
    last_name: "Niles",
    email: "cniles6@gmail.com",
    gender: "Female",
    ip_address: "227.80.150.116",
    address: "Farshūţ",
    photo:
      "https://robohash.org/nesciuntcorporisconsequatur.jpg?size=50x50&set=set1",
    company: "Knowledge",
    department: "Engineering",
    Salary: "20000",
    about: "React",
  },
  {
    id: 8,
    first_name: "Madalyn",
    last_name: "Willshear",
    email: "mwillshear7@gmail.com",
    gender: "Female",
    ip_address: "152.227.67.16",
    address: "Metapán",
    photo: "https://robohash.org/dignissimosquiasit.jpg?size=50x50&set=set1",
    company: "Knowledge",
    department: "Legal",
    Salary: "20000",
    about: "posuere nonummy integer non velit donec diam neque vestibulum eget",
  },
  {
    id: 9,
    first_name: "Kristopher",
    last_name: "Parfett",
    email: "kparfett8@gmail.com",
    gender: "Male",
    ip_address: "56.56.12.200",
    address: "Żabnica",
    photo: "https://robohash.org/utipsamiure.bmp?size=50x50&set=set1",
    company: "Knowledge",
    department: "Marketing",
    Salary: "20000",
    about: "Python",
  },
  {
    id: 10,
    first_name: "Lissi",
    last_name: "Kilbride",
    email: "lkilbride9@gmail.com",
    gender: "Female",
    ip_address: "120.57.214.203",
    address: "Datong",
    photo: "https://robohash.org/corporisquisunt.png?size=50x50&set=set1",
    company: "Knowledge",
    department: "Business Development",
    Salary: "20000",
    about: "C#",
  },
];
export { data };
